//! Shared state of the negotiated core profile.
//!
//! The state owns the durable stores (generation, state root, run index),
//! the handle registry, the cached per-run journals and the live ACK-gated
//! deliveries. It deliberately does **not** own Session maps, run
//! terminals, retries or event sequences — those stay with the shared
//! [`echo_agent::acp::AcpConnectionServices`] and the framework driver.

use echo_agent::acp::AcpConnectionServices;
use echo_agent::agent::EventEnvelope;
use echo_agent::error::{ReactError, Result};
use echo_agent::state::FileRuntimeStateStore;
use echo_agent::state::journal::{EventJournal as _, SegmentedFileEventJournal};
use echo_sdk_protocol::capability::{
    CapabilityDeclaration, ECHO_AGENT_META_KEY, EchoAgentCapability, EchoLimits,
    ExtensionCapability,
};
use echo_sdk_protocol::scalar::{WireDuration, WireU64};
use std::collections::HashMap;
use std::path::Path;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex, OnceLock};
use tokio::sync::Notify;

use super::events::StreamDelivery;
use super::handles::HandleRegistry;
use super::persistence::{CorePersistence, RecoveredRun};
use crate::HostError;
use crate::config::SdkProfileLimits;
use crate::factory::PreparedAgentDefinition;

/// Embedded source-compatibility digest generated by the contract export
/// (`contracts/sdk/source-contract.json`). The Host embeds only this small
/// generated artifact — never the large inventory files.
const SOURCE_CONTRACT_JSON: &str = include_str!("../../../contracts/sdk/source-contract.json");
const MAX_CACHED_JOURNALS: usize = 1024;

pub(crate) struct CoreProfileState {
    services: OnceLock<Arc<AcpConnectionServices>>,
    pub handles: HandleRegistry,
    pub persistence: CorePersistence,
    pub limits: SdkProfileLimits,
    pub default_definition: Arc<PreparedAgentDefinition>,
    #[allow(dead_code)]
    pub default_agent_handle: echo_sdk_protocol::handle::WireHandle,
    pub state_store: Arc<FileRuntimeStateStore>,
    pub recovered_runs: Vec<Arc<RecoveredRun>>,
    pub advertisement: EchoAgentCapability,
    pub session_factory: crate::factory::CoreProfileSessionFactory,
    journals: Mutex<HashMap<String, Arc<SegmentedFileEventJournal<EventEnvelope>>>>,
    deliveries: Mutex<HashMap<String, Arc<StreamDelivery>>>,
    #[cfg(feature = "sdk-extension-bridge")]
    pub extension_shared: Arc<super::extension_bridge::ExtensionBridgeShared>,
    #[cfg(feature = "sdk-extension-bridge")]
    #[allow(dead_code)]
    pub extension_bridge: Arc<super::extension_bridge::ExtensionBridge>,
    #[cfg(feature = "sdk-facade-adapters")]
    pub facade: super::facade::SessionFacadeRuntime,
    pending_settlements: AtomicUsize,
    settlement_notify: Notify,
    settlement_error: Mutex<Option<String>>,
}

impl CoreProfileState {
    /// Build the profile state for one Host process: open durable stores,
    /// advance the generation, and load recovered runs with their journals.
    /// The Host default Agent definition carries the state store so every
    /// Session (standard or extension) checkpoints into the same root.
    pub fn install(
        state_root: &Path,
        limits: SdkProfileLimits,
        framework: echo_agent::config::FrameworkConfig,
        llm_client: std::sync::Arc<dyn echo_agent::llm::LlmClient>,
    ) -> std::result::Result<std::sync::Arc<Self>, HostError> {
        let persistence = CorePersistence::open(state_root)
            .map_err(|error| HostError::Config(error.to_string()))?;
        let state_store = persistence.state_store();
        #[cfg(feature = "sdk-extension-bridge")]
        let extension_shared = Arc::new(super::extension_bridge::ExtensionBridgeShared::new());
        #[cfg(feature = "sdk-extension-bridge")]
        let extension_bridge: Option<Arc<super::extension_bridge::ExtensionBridge>>;
        #[allow(unused_mut)]
        let mut default_definition = Arc::new(PreparedAgentDefinition::new(
            framework,
            llm_client,
            Some(state_store.clone()),
            true,
        ));
        // The bridge is created unbound (the state does not exist yet) and
        // captured by the default definition so every Session Agent built
        // from it resolves registered extensions; the state binds itself
        // immediately after construction below.
        #[cfg(feature = "sdk-extension-bridge")]
        {
            let bridge = Arc::new(super::extension_bridge::ExtensionBridge::unbound(
                extension_shared.clone(),
            ));
            default_definition = Arc::new(
                default_definition
                    .as_ref()
                    .clone()
                    .with_extension_bridge(bridge.clone()),
            );
            extension_bridge = Some(bridge);
        }
        let mut recovered_runs = Vec::new();
        for mut recovered in persistence
            .load_recovered_runs()
            .map_err(|error| HostError::Config(error.to_string()))?
        {
            // Open each recovered journal now: the last durable sequence is
            // the authoritative watermark for `run/get` and replay floors.
            let journal = persistence
                .open_run_journal(&recovered.record.run_id)
                .map_err(|error| HostError::Config(error.to_string()))?;
            let journal_sequence = journal.last_sequence();
            persistence
                .validate_recovered_journal(&recovered, journal_sequence)
                .map_err(|error| HostError::Config(error.to_string()))?;
            recovered.last_sequence = journal_sequence;
            recovered_runs.push(Arc::new(recovered));
        }
        let advertisement = build_advertisement(&limits)?;
        let handles = HandleRegistry::new(persistence.generation(), limits.max_open_handles);
        let (default_agent_handle, _) = handles
            .register_agent(
                default_definition.clone(),
                HandleRegistry::config_fingerprint(
                    &echo_sdk_protocol::methods::AgentConfigWire::HostDefault,
                ),
            )
            .map_err(|error| HostError::Config(error.message))?;
        let session_factory = crate::factory::CoreProfileSessionFactory::new(
            default_definition.clone(),
            limits.max_open_handles,
        );
        #[cfg(feature = "sdk-facade-adapters")]
        let facade = super::facade::SessionFacadeRuntime::new(&limits);
        let state = Arc::new(Self {
            services: OnceLock::new(),
            handles,
            persistence,
            limits,
            default_definition,
            default_agent_handle,
            state_store,
            recovered_runs,
            advertisement,
            session_factory,
            journals: Mutex::new(HashMap::new()),
            deliveries: Mutex::new(HashMap::new()),
            #[cfg(feature = "sdk-extension-bridge")]
            extension_shared,
            #[cfg(feature = "sdk-extension-bridge")]
            extension_bridge: extension_bridge.clone().ok_or_else(|| {
                HostError::Config("extension bridge was not constructed".to_string())
            })?,
            #[cfg(feature = "sdk-facade-adapters")]
            facade,
            pending_settlements: AtomicUsize::new(0),
            settlement_notify: Notify::new(),
            settlement_error: Mutex::new(None),
        });
        #[cfg(feature = "sdk-extension-bridge")]
        if let Some(bridge) = extension_bridge {
            bridge.bind_state(state.clone());
        }
        Ok(state)
    }

    /// Meta key under which the Session context carries its definition id.
    pub fn definition_meta_key(&self) -> &'static str {
        crate::factory::DEFINITION_META_KEY
    }

    /// Register a definition so future Sessions can resolve it.
    pub fn register_definition(
        &self,
        definition: &Arc<PreparedAgentDefinition>,
    ) -> std::result::Result<(), String> {
        self.session_factory.register_definition(definition.clone())
    }

    /// Bind the shared connection runtime once per connection.
    pub fn bind_services(&self, services: Arc<AcpConnectionServices>) {
        let _ = self.services.set(services);
    }

    pub fn services(&self) -> Result<Arc<AcpConnectionServices>> {
        self.services
            .get()
            .cloned()
            .ok_or_else(|| ReactError::Other("connection services are not bound".to_string()))
    }

    /// Open (or fetch the cached) journal for one run.
    pub fn journal(&self, run_id: &str) -> Result<Arc<SegmentedFileEventJournal<EventEnvelope>>> {
        let mut journals = self
            .journals
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        if let Some(cached) = journals.get(run_id) {
            return Ok(cached.clone());
        }
        let journal = self
            .persistence
            .open_run_journal(run_id)
            .map_err(|error| ReactError::Other(error.to_string()))?;
        if journals.len() >= MAX_CACHED_JOURNALS
            && let Some(oldest) = journals.keys().next().cloned()
        {
            journals.remove(&oldest);
        }
        journals.insert(run_id.to_string(), journal.clone());
        Ok(journal)
    }

    pub fn remove_journal(&self, run_id: &str) {
        self.journals
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .remove(run_id);
    }

    pub fn cleanup_settled_run(&self, run_id: &str) {
        self.remove_delivery_for_run(run_id);
    }

    pub fn begin_settlement(&self) {
        self.pending_settlements.fetch_add(1, Ordering::AcqRel);
    }

    pub fn finish_settlement(&self, result: std::result::Result<(), String>) {
        if let Err(error) = result {
            *self
                .settlement_error
                .lock()
                .unwrap_or_else(|poisoned| poisoned.into_inner()) = Some(error);
        }
        let _ =
            self.pending_settlements
                .fetch_update(Ordering::AcqRel, Ordering::Acquire, |current| {
                    Some(current.saturating_sub(1))
                });
        self.settlement_notify.notify_waiters();
    }

    pub async fn wait_settlements(
        &self,
        timeout: std::time::Duration,
    ) -> std::result::Result<(), String> {
        let drained = tokio::time::timeout(timeout, async {
            while self.pending_settlements.load(Ordering::Acquire) != 0 {
                self.settlement_notify.notified().await;
            }
        })
        .await
        .map_err(|_| "timed out waiting for durable run settlements".to_string());
        drained?;
        self.settlement_error
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .take()
            .map_or(Ok(()), Err)
    }

    pub fn register_delivery(&self, delivery: Arc<StreamDelivery>) {
        self.deliveries
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .insert(delivery.stream_handle().id.clone(), delivery);
    }

    pub fn remove_delivery(&self, stream_id: &str) {
        self.deliveries
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .remove(stream_id);
    }

    pub fn remove_delivery_for_run(&self, run_id: &str) {
        self.deliveries
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .retain(|_, delivery| delivery.run_id() != run_id);
    }

    pub fn delivery(&self, stream_id: &str) -> Option<Arc<StreamDelivery>> {
        self.deliveries
            .lock()
            .unwrap_or_else(|error| error.into_inner())
            .get(stream_id)
            .cloned()
    }

    /// Recovered runs of one session, in index order.
    pub fn recovered_runs_of_session(&self, session_id: &str) -> Vec<Arc<RecoveredRun>> {
        self.recovered_runs
            .iter()
            .filter(|recovered| recovered.record.session_id == session_id)
            .cloned()
            .collect()
    }

    /// Flush cached journals during the bounded shutdown chain.
    pub fn flush_journals(&self) -> std::result::Result<(), String> {
        let journals = self
            .journals
            .lock()
            .unwrap_or_else(|error| error.into_inner());
        for journal in journals.values() {
            journal
                .sync_data()
                .map_err(|error| format!("failed to flush run journal: {error}"))?;
        }
        Ok(())
    }
}

/// The capability advertisement published under
/// `agentCapabilities._meta.echo_agent`. Feature sets come from the actual
/// compilation; the four core families are declared, everything else stays
/// unadvertised until its plan lands.
fn build_advertisement(
    limits: &SdkProfileLimits,
) -> std::result::Result<EchoAgentCapability, HostError> {
    let contract_digest = echo_sdk_protocol::schema::extension_contract_digest();
    let source_contract: serde_json::Value =
        serde_json::from_str(SOURCE_CONTRACT_JSON).map_err(|error| {
            HostError::Config(format!("embedded source contract is invalid: {error}"))
        })?;
    let source_digest = source_contract
        .get("aggregate_digest")
        .and_then(serde_json::Value::as_str)
        .ok_or_else(|| HostError::Config("source contract missing aggregate_digest".to_string()))?
        .to_string();
    #[allow(unused_mut)]
    let mut capabilities = vec![
        CapabilityDeclaration {
            capability: ExtensionCapability::AgentLifecycle,
            required: false,
        },
        CapabilityDeclaration {
            capability: ExtensionCapability::SessionHandles,
            required: false,
        },
        CapabilityDeclaration {
            capability: ExtensionCapability::Runs,
            required: false,
        },
        CapabilityDeclaration {
            capability: ExtensionCapability::EventReplay,
            required: false,
        },
    ];
    // The extension bridge is advertised only when the Host actually
    // compiled it (plan 06, design §10.2): a capability declaration without
    // the compiled handlers would be a false advertisement.
    #[cfg(feature = "sdk-extension-bridge")]
    capabilities.push(CapabilityDeclaration {
        capability: ExtensionCapability::ExtensionBridge,
        required: false,
    });
    // The facade runtime compiles the generic invoke surface and the
    // admission ladder; family capabilities land with their handlers
    // (family adapters) — never before. The typed task handlers bind to
    // the Session's own TaskRevisionService.
    #[cfg(feature = "sdk-facade-adapters")]
    capabilities.push(CapabilityDeclaration {
        capability: ExtensionCapability::FeatureSurfaces,
        required: false,
    });
    #[cfg(feature = "sdk-facade-adapters")]
    capabilities.push(CapabilityDeclaration {
        capability: ExtensionCapability::TaskGraph,
        required: false,
    });
    #[cfg(all(feature = "sdk-facade-adapters", feature = "framework-subagent"))]
    capabilities.push(CapabilityDeclaration {
        capability: ExtensionCapability::Subagents,
        required: false,
    });
    #[cfg(feature = "sdk-facade-adapters")]
    capabilities.push(CapabilityDeclaration {
        capability: ExtensionCapability::StructuredOutput,
        required: false,
    });
    let advertisement = EchoAgentCapability {
        extension_protocol_version: echo_sdk_protocol::EXTENSION_PROTOCOL_VERSION,
        contract_digest,
        source_contract_digest: source_digest,
        features: crate::features::compiled_leaf_features(),
        capabilities,
        limits: EchoLimits {
            max_message_bytes: WireU64::from_u64(limits.max_frame_bytes),
            max_stream_buffer_events: WireU64::from_u64(
                u64::try_from(limits.max_outstanding_live_events).unwrap_or(u64::MAX),
            ),
            max_callback_concurrency: limits
                .max_callback_concurrency
                .try_into()
                .unwrap_or(u32::MAX),
            callback_timeout: WireDuration {
                seconds: WireU64::from_u64(limits.callback_timeout_secs),
                nanos: 0,
            },
            max_replay_events: WireU64::from_u64(
                u64::try_from(limits.max_replay_events).unwrap_or(u64::MAX),
            ),
            max_structured_output_bytes: WireU64::from_u64(262_144),
            max_outstanding_live_events: WireU64::from_u64(
                u64::try_from(limits.max_outstanding_live_events).unwrap_or(u64::MAX),
            ),
            max_stream_buffer_bytes: WireU64::from_u64(
                u64::try_from(limits.max_event_bytes)
                    .unwrap_or(u64::MAX)
                    .saturating_mul(
                        u64::try_from(limits.max_outstanding_live_events).unwrap_or(u64::MAX),
                    ),
            ),
            max_replay_bytes: WireU64::from_u64(
                u64::try_from(limits.max_replay_bytes).unwrap_or(u64::MAX),
            ),
            max_open_handles: WireU64::from_u64(
                u64::try_from(limits.max_open_handles).unwrap_or(u64::MAX),
            ),
            max_registered_extensions: WireU64::from_u64(
                u64::try_from(limits.max_registered_extensions).unwrap_or(u64::MAX),
            ),
            max_extension_descriptor_bytes: WireU64::from_u64(
                u64::try_from(limits.max_extension_descriptor_bytes).unwrap_or(u64::MAX),
            ),
            max_extension_payload_bytes: WireU64::from_u64(
                u64::try_from(limits.max_extension_payload_bytes).unwrap_or(u64::MAX),
            ),
            max_extension_stream_bytes: WireU64::from_u64(
                u64::try_from(limits.max_extension_stream_bytes).unwrap_or(u64::MAX),
            ),
            max_inflight_extension_invocations: WireU64::from_u64(
                u64::try_from(limits.max_extension_invocations).unwrap_or(u64::MAX),
            ),
            max_facade_resources: WireU64::from_u64(
                u64::try_from(limits.max_facade_resources).unwrap_or(u64::MAX),
            ),
            max_facade_streams: WireU64::from_u64(
                u64::try_from(limits.max_facade_streams).unwrap_or(u64::MAX),
            ),
            max_facade_page_items: WireU64::from_u64(
                u64::try_from(limits.max_facade_page_items).unwrap_or(u64::MAX),
            ),
            max_facade_operation_args: WireU64::from_u64(
                u64::try_from(limits.max_facade_operation_args).unwrap_or(u64::MAX),
            ),
        },
    };
    let problems = advertisement.validate_shape();
    if !problems.is_empty() {
        return Err(HostError::Config(format!(
            "core profile advertisement failed validation: {}",
            problems.join("; ")
        )));
    }
    Ok(advertisement)
}

// The advertisement feature list is derived from the compiled Cargo
// feature set (`crate::features`), never duplicated here or in config.

pub(crate) fn advertisement_meta(
    advertisement: &EchoAgentCapability,
) -> Option<(String, serde_json::Value)> {
    Some((
        ECHO_AGENT_META_KEY.to_string(),
        serde_json::to_value(advertisement).ok()?,
    ))
}
